version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    rust: '1.75'
  jobs:
    post_install:
    - pip install sphinx-book-theme
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true
