version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_install:
      - pip install pydata-sphinx-theme==0.15.2 sphinx==6.2.1 sphinx-book-theme==1.1.0
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
