version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    rust: '1.75'
  apt_packages:
  - freeglut3-dev
  - xvfb
  - x11-utils
  commands:
  - nohup Xvfb $DISPLAY -screen 0 1400x900x24 -dpi 96 +extension RANDR +render &
  - asdf plugin add uv
  - asdf install uv latest
  - asdf global uv latest
  - uv venv
  - uv pip install .[docs]
  - .venv/bin/python -m sphinx -T -b html -d docs/build/doctrees -D language=en docs/source/ $READTHEDOCS_OUTPUT/html
