version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_install:
      - pip install sphinx-book-theme==0.3.3
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
