[build-system]
build-backend = "maturin"
requires = ["maturin>=1.3,<2.0"]

[project]
authors = [{name = "Jérome Eertmans", email = "jeertmans@icloud.com"}]
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy"
]
dynamic = ["version"]
license = {file = "LICENSE.md"}
name = "differt-core"
readme = "README.md"
requires-python = ">=3.9"

[tool.maturin]
features = ["pyo3/extension-module"]
