# Default command (list all commands)
default:
  @just --list

# Clean build artifacts
clean:
  rm -rf build

# Build docs
build builder="html" *OPTIONS="-W --keep-going":
  uv run sphinx-build -M {{builder}} source build {{OPTIONS}}

# Build docs in "draft" mode
draft *ARGS:
  NB_OFF="1" just build {{ARGS}}

# Check links
linkcheck *ARGS: (draft "linkcheck" ARGS)

alias check := linkcheck
