# Check for common grammar and spelling mistakes
name: LanguageTool

on:
  pull_request:
  workflow_dispatch:

jobs:
  languagetool-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Strip cell output
      run: |
        pip install nbstripout
        find . -name '*.ipynb' -exec nbstripout {} +

    - name: Check and report
      uses: reviewdog/action-languagetool@v1
      with:
        reporter: github-pr-review
        patterns: '*.md src/**.rs python/differt/**.py docs/source/**.md docs/source/**.ipynb'
        level: warning
