# Check for common grammar and spelling mistakes
name: LanguageTool

on:
  pull_request:
  workflow_dispatch:

jobs:
  languagetool-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check and report
      uses: reviewdog/action-languagetool@v1
      with:
        reporter: github-pr-review
        patterns: '**'
        level: warning
