# Lint code and (optionally) apply fixes
name: Lint code

on:
  pull_request:
  push:
    branches: [main]
  schedule:
  - cron: 0 0 * * 1 # Every monday
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install pre-commit
      uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
      with:
        install-only: true

    - name: Run autoupdate
      run: prek update

    - name: Create a pull request with updated versions
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        branch: update/pre-commit-hooks
        title: 'chore(deps): update pre-commit hooks'
        commit-message: 'chore(deps): update pre-commit hooks'
        labels: |
          ci
          dependencies

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt

    - name: Install and run pre-commit
      uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
