name: Publish Python Packages
on:
  pull_request:
    branches:
    - main
    paths:
    - '**/pyproject.toml'
    - '**/Cargo.toml'
    - uv.lock
    - differt/src/**/.py
    - differt-core/{src,python}/**/*.{py,rs}
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      publish-differt:
        type: boolean
        description: Publish differt
      publish-differt-core:
        type: boolean
        description: Publish differt-core

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-differt-core-linux-wheels:
    name: Build linux-${{ matrix.platform.target}} wheels for differt-core
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
        - runner: ubuntu-24.04
          target: x86_64
        - runner: ubuntu-24.04
          target: x86
        - runner: ubuntu-24.04
          target: aarch64
        - runner: ubuntu-24.04
          target: armv7
        - runner: ubuntu-24.04
          target: s390x
        - runner: ubuntu-24.04
          target: ppc64le
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: |
          3.14
          3.14t

    - name: Build wheels
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        target: ${{ matrix.platform.target }}
        args: --release --out dist --find-interpreter
        sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        manylinux: auto
        working-directory: differt-core

    - name: Upload wheels
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-core-wheels-linux-${{ matrix.platform.target }}
        path: differt-core/dist

  build-differt-core-musllinux-wheels:
    name: Build musl-${{ matrix.platform.target}} wheels for differt-core
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
        - runner: ubuntu-24.04
          target: x86_64
        - runner: ubuntu-24.04
          target: x86
        - runner: ubuntu-24.04
          target: aarch64
        - runner: ubuntu-24.04
          target: armv7
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: |
          3.14
          3.14t

    - name: Build wheels
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        target: ${{ matrix.platform.target }}
        args: --release --out dist --find-interpreter
        sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        manylinux: musllinux_1_2
        working-directory: differt-core

    - name: Upload wheels
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-core-wheels-musllinux-${{ matrix.platform.target }}
        path: differt-core/dist

  build-differt-core-windows-wheels:
    name: Build windows-${{ matrix.platform.target}} wheels for differt-core
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
        - runner: windows-latest
          target: x64
        - runner: windows-latest
          target: x86
        python-version:  # Bug: co-install fails (see Maturin's README.md)
        - '3.14'
        - 3.14t
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.platform.python-version }}
        architecture: ${{ matrix.platform.target }}

    - name: Build wheels
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        target: ${{ matrix.platform.target }}
        args: --release --out dist --find-interpreter
        sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        working-directory: differt-core

    - name: Upload wheels
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-core-wheels-windows-${{ matrix.platform.target }}
        path: differt-core/dist

  build-differt-core-macos-wheels:
    name: Build macos-${{ matrix.platform.target}} wheels for differt-core
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
        - runner: macos-latest
          target: x86_64
        - runner: macos-latest
          target: aarch64
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: |
          3.14
          3.14t

    - name: Build wheels
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        target: ${{ matrix.platform.target }}
        args: --release --out dist --find-interpreter
        sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        working-directory: differt-core

    - name: Upload wheels
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-core-wheels-macos-${{ matrix.platform.target }}
        path: differt-core/dist

  build-differt-core-sdist:
    name: Build sdist for differt-core
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build sdist
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        command: sdist
        args: --out dist
        working-directory: differt-core

    - name: Upload sdist
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-core-wheels-sdist
        path: differt-core/dist

  release-differt-core:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event.inputs.publish-differt-core
    name: Release differt-core
    runs-on: ubuntu-latest
    needs: [build-differt-core-linux-wheels, build-differt-core-musllinux-wheels, build-differt-core-windows-wheels, build-differt-core-macos-wheels, build-differt-core-sdist]
    environment: release
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Download build wheels
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: differt-core/dist
        pattern: differt-core-wheels-*

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
      with:
        subject-path: differt-core/dist/differt-core-wheels-*

    - name: Publish to PyPI
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        command: upload
        args: --non-interactive --skip-existing dist/differt-core-wheels-*/*
        working-directory: differt-core

  build-differt:
    name: Build DiffeRT
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      with:
        enable-cache: true

    - name: Build package
      run: uv build --package differt -o differt/dist

    - name: Upload sdist
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-wheels-sdist
        path: differt/dist/differt-*.tar.gz

    - name: Upload wheels any
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: differt-wheels-any
        path: differt/dist/differt-*.whl

  release-differt:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event.inputs.publish-differt
    name: Release DiffeRT
    runs-on: ubuntu-latest
    needs: [build-differt]
    environment: release
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Download build wheels
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: differt/dist
        pattern: differt-wheels-*
        merge-multiple: true

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
      with:
        subject-path: differt/dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
      with:
        packages-dir: differt/dist/
        skip-existing: true
