name: Publish differt Python Package
on:
  push:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install poetry

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: poetry

    - name: Build wheels
      run: poetry build

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
