# Check that minimum Rust supported version compiles this project
name: MSRV check

on:
  pull_request:
    paths:
    - '**.rs'
    - Cargo.toml
  workflow_dispatch:

jobs:
  msrv_check:
    defaults:
      run:
        working-directory: differt-core
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install Cargo MSRV
      uses: taiki-e/install-action@065d6a08a14e61e89fb0a4c10eecdbdef39c7d8e # v2.85.4
      with:
        tool: cargo-msrv

    - name: Check MSRV
      run: cargo msrv verify -- cargo check --all-features
